version: '3.9'

services:
  web:
    build: .
    container_name: lms_app
    command: daphne -b 0.0.0.0 -p 8001 root.asgi:application
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - minio
      - redis
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]

  lms_celery:
    build: .
    container_name: lms_celery
    command: celery -A root worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]

  lms_celery_beat:
    build: .
    container_name: lms_celery_beat
    command: celery -A root beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # PostgreSQL
  db:
    image: postgres:15
    container_name: lms_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
  minio_data:
